%YAML:1.0

logger: 
  log_path: "/user_space/robot/log/robot_log/"
  log_name: "robot_transfer_station_logger"
  log_prefix: "robot_transfer_station_logger_"
  single_log_max_size_MB: 10
  log_max_cnt: 50
  # trace:0, debug:1, info:2, warn:3, error:4, critical:5, off:6
  log_level_num: 2
  is_asyn_log: true
  log_queue_size: 8192
  log_thread_cnt: 4
  is_console_log: true


udp_info:
  ip_addr: "192.168.8.1"
  ip_port: 9002

node_info:
  vr_pose_arr_topic_name: "vr_pose_arr"
  vr_key_status_topic_name: "vr_key_status"
  imu_pub_topic_name: "imu_data_arr"
  arm_path: "/user_space/gac_ros_ws/install/gac_arm_cpp/lib/gac_arm_cpp"



# serial_com_info:
#   is_start_up: true
#   serial_port: "/dev/ttyUSB0"
#   baud_rate: 115200
#   # Flow ctrl: 0->none, 1->software, 2->hardware
#   flow_ctrl: 0
#   # Byte size: 5->fivebits, 6->sixbits, 7->sevenbits, 8->eightbits
#   byte_size: 8
#   # Parity: 0->none, 1->odd, 2->even, 3->mark, 4->space
#   parity: 0
#   # Stop Bit: 1->one, 2->two, 3->one_point_five
#   stop_bit: 1
#   max_msg_len: 1024
#   ble_dev_idx: 0

# imu_ble_info:
#   imu_ble_dev_cnt: 5
#   imu_addr_type: "1"
#   # imu_mac_addr_vec: [
#   #   "C8AE8B4EF7E9"]
#   # imu_mac_addr_vec: [
#   #   "D42BD8397123",
#   #   "EBEA38646EB3",
#   #   "DABB411CF6C0"]
#   imu_mac_addr_vec: [
#     "C8AE8B4EF7E9",
#     "D42BD8397123",
#     "DABB411CF6C0",
#     "FD7C93C918FD",
#     "EBEA38646EB3"]


# vr_pose_client:
#   is_start_up: false
#   ip_addr: "192.168.1.105"
#   ip_port: 9002
#   vr_pose_topic_name: "vr_pose_arr"
#   vr_key_topic_name: "vr_key_status"
